export const PERMISSIONS = {
  PRODUCT_READ: 'PRODUCT_READ',
  PRODUCT_WRITE: 'PRODUCT_WRITE',
  INVOICE_READ: 'INVOICE_READ',
  INVOICE_ISSUE: 'INVOICE_ISSUE',
  SALE_READ: 'SALE_READ',
  SALE_WRITE: 'SALE_WRITE',
  USER_MANAGE: 'USER_MANAGE',
  TENANT_MANAGE: 'TENANT_MANAGE',
  AUDIT_READ: 'AUDIT_READ',
  CATEGORY_READ: 'CATEGORY_READ',
  CATEGORY_WRITE: 'CATEGORY_WRITE',
  PLATFORM_ADMIN: 'PLATFORM_ADMIN',
  SUPPORT_MANAGE: 'SUPPORT_MANAGE',
} as const;

export type Permission = keyof typeof PERMISSIONS;

export const ROLES = {
  PLATFORM_ADMIN: 'PLATFORM_ADMIN',
  TENANT_ADMIN: 'TENANT_ADMIN',
  OPERATOR: 'OPERATOR',
  READER: 'READER',
  AFFILIATE: 'AFFILIATE',
  ATENDENTE: 'ATENDENTE',
} as const;

export type Role = keyof typeof ROLES;

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  PLATFORM_ADMIN: [
    'PRODUCT_READ',
    'PRODUCT_WRITE',
    'INVOICE_READ',
    'INVOICE_ISSUE',
    'SALE_READ',
    'SALE_WRITE',
    'USER_MANAGE',
    'TENANT_MANAGE',
    'AUDIT_READ',
    'CATEGORY_READ',
    'CATEGORY_WRITE',
    'PLATFORM_ADMIN',
    'SUPPORT_MANAGE',
  ],
  TENANT_ADMIN: [
    'PRODUCT_READ',
    'PRODUCT_WRITE',
    'INVOICE_READ',
    'INVOICE_ISSUE',
    'SALE_READ',
    'SALE_WRITE',
    'USER_MANAGE',
    'TENANT_MANAGE',
    'AUDIT_READ',
    'CATEGORY_READ',
    'CATEGORY_WRITE',
  ],
  OPERATOR: [
    'PRODUCT_READ',
    'PRODUCT_WRITE',
    'INVOICE_READ',
    'INVOICE_ISSUE',
    'SALE_READ',
    'SALE_WRITE',
    'CATEGORY_READ',
    'CATEGORY_WRITE',
  ],
  READER: ['PRODUCT_READ', 'INVOICE_READ', 'SALE_READ', 'CATEGORY_READ'],
  AFFILIATE: [],
  ATENDENTE: ['SUPPORT_MANAGE'],
};
